# D:\Coding\JAVABootcamp\Banking\docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: banking-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: